---
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: pac-1
  annotations:
  annotations:
    pipelinesascode.tekton.dev/on-event: "[pull_request]"
    # Use pipelines-svc-0.1-6e05d4d branch since we are using openshift-pipeline/tektoncd-results and not upstream
    pipelinesascode.tekton.dev/on-target-branch: "[pipelines-svc-0.1-6e05d4d]"
    pipelinesascode.tekton.dev/max-keep-runs: "5"
spec:
  pipelineRef:
    name: demop
    bundle: ttl.sh/demop@sha256:545109c1859f7b1d9db6593829307c86615ef9c0e73dde94d01cfd6bec658e81