---
# Triggers Tekton Results watcher image build on pull request
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: tekton-results-watcher-on-pull-request
  annotations:
    pipelinesascode.tekton.dev/on-event: "[pull_request]"
    # Use pipelines-svc-0.1-6e05d4d branch since we are using openshift-pipeline/tektoncd-results and not upstream
    pipelinesascode.tekton.dev/on-target-branch: "[pipelines-svc-0.1-6e05d4d]"
    pipelinesascode.tekton.dev/max-keep-runs: "5"
spec:
  params:
    - name: git-url
      value: "{{repo_url}}"
    - name: revision
      value: "{{revision}}"
    - name: output-image
      value: "quay.io/redhat-appstudio/pull-request-builds:tekton-results-watcher-{{revision}}"
    - name: dockerfile
      value: images/watcher/Dockerfile
  pipelineRef:
    name: docker-build
    bundle: quay.io/redhat-appstudio/hacbs-core-service-templates-bundle:latest
  workspaces:
    - name: workspace
      persistentVolumeClaim:
        claimName: app-studio-default-workspace
